on: push
name: Publish On Dev
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.FTP_URL_GUTHUBDEPLOY }}
        ftp-username: ${{ secrets.FTP_USER_GUTHUBDEPLOY }}
        ftp-password: ${{ secrets.FTP_PASSWORD_GITHUBDEPLOY }}
