on: push
name: Publish On Dev
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftps://unmus.de/unmus/dev/wp-content/plugins/hello-dolly-for-your-song/
        ftp-username: GitHubDeploy
        ftp-password: ${{ secrets.FTP_PASSWORD_GITHUBDEPLOY }}
